spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.resources.static-locations: classpath:/

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.151:8761/eureka/
spring:
  application:
    name: websocket
